name: Pr CICD
on: [pull_request]
jobs:
  Build:
    #runs-on: self-hosted
    runs-on:  ubuntu-latest
    steps:
      - run: echo OK
  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - run: echo OK





