name: Main CICD
on:
  workflow_dispatch:
  push:
    branches:
        - 'main'
jobs:
  Reuse:
    uses: 'C:\Users\UdayaCharagundla\OneDrive-Kyndryl\Desktop\roboproj\learn-github-actions\.github\workflows\sample-reusable.yml@main'





